# SPDX-FileCopyrightText: Copyright © DUNE Project contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception

Module: dune-geometry
Version: 2.10-git
Author: The Dune Core developers
Maintainer: dune-devel@lists.dune-project.org
Description: Geometry Transformations, Reference Elements and Quadrature Rules
URL: https://gitlab.dune-project.org/core/dune-geometry
Depends: dune-common (>= 2.9)
Whitespace-Hook: Yes
